services:
  collector:
    build: .
    volumes:
      - .:/app
      - ./output:/output
    command: >
      sh -c "python -m src.collector"
    mem_limit: 400m
    cpus: 1.5
  
  mailer:
    build: .
    volumes:
      - .:/app
      - ./output:/output
    command: >
      sh -c "python -m src.mailer"
    mem_limit: 400m
    cpus: 1.5